[server]
enableStaticServing = true

[runner]
# Prevent watching PyTorch modules which cause errors
moduleExcludedForWatching = ["torch"]

[logger]
# Optional: reduce log level for cleaner output
level = "warning" 